export type Source = "Seputar HMGF" | "SEG News" | "Geolibrary";
export type Article = { id: string; slug: string; title: string; image: string; author: string; date: string; category: string; course: string; paragraphs: string[]; source: Source; published: boolean };
const gids: Record<Source, string> = { "Seputar HMGF": "1262503653", "SEG News": "840471671", Geolibrary: "5080467" };
const months: Record<string, string> = { januari: "Januari", februari: "Februari", maret: "Maret", april: "April", mei: "Mei", juni: "Juni", juli: "Juli", agustus: "Agustus", september: "September", oktober: "Oktober", november: "November", desember: "Desember" };

export function escapeHtml(value: unknown): string { return String(value ?? "").replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char] || char)); }
function value(record: Record<string, unknown>, keys: string[]): string { for (const key of keys) if (record[key] != null && String(record[key]).trim()) return String(record[key]).trim(); return ""; }
function blank(record: Record<string, unknown>, test: (value: string) => boolean): string { return Object.entries(record).find(([key, item]) => key.startsWith("_column_") && test(String(item).trim()))?.[1] as string || ""; }
function published(record: Record<string, unknown>): boolean { const raw = value(record, ["Published", "published", "Published (TRUE/FALSE)", "Status"]) || blank(record, item => /^(true|false|1|0)$/i.test(item)); return /^(true|1)$/i.test(raw.trim()); }
function date(valueRaw: string): string { const raw = valueRaw.trim(); const match = raw.match(/^(\w+)\s+(\d{1,2}),?\s+(\d{4})$/i); if (match && months[match[1].toLowerCase()]) return `${match[2]} ${months[match[1].toLowerCase()]} ${match[3]}`; return raw || "-"; }
function normalize(record: Record<string, unknown>, source: Source): Article | null { const title = value(record, ["Judul Konten / Berkas", "Judul Berita", "Judul", "judul", "title"]); if (!title || !published(record)) return null; const paragraphs = Array.from({ length: 13 }, (_, i) => value(record, [`Isi ${i + 1}`, `isi_${i + 1}`, i === 0 ? "Isi Paragraf / Gambar" : ""])).filter(Boolean); return { id: value(record, ["ID", "Id", "id"]) || title, slug: title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""), title, image: value(record, ["Gambar Link", "gambar_hero", "Gambar"]), author: value(record, ["Penulis", "penulis"]) || "Redaksi HMGF", date: date(value(record, ["Tanggal Upload", "Tanggal", "tanggal", "date"]) || blank(record, item => /(?:januari|februari|maret|april|mei|juni|juli|agustus|september|oktober|november|desember)\s+\d{1,2},?\s+\d{4}/i.test(item))), category: value(record, ["Kategori Utama", "Kategori", "kategori"]) || "Geofisika", course: value(record, ["Mata Kuliah"]), paragraphs, source, published: true }; }
function parseCsv(text: string): Record<string, unknown>[] { const rows: string[][] = []; let row: string[] = [], field = "", quoted = false; for (let i = 0; i < text.length; i++) { const char = text[i], next = text[i + 1]; if (char === '"') { if (quoted && next === '"') { field += '"'; i++; } else quoted = !quoted; } else if (char === "," && !quoted) { row.push(field); field = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && next === "\n") i++; row.push(field); rows.push(row); row = []; field = ""; } else field += char; } if (field || row.length) { row.push(field); rows.push(row); } const headers = (rows.shift() || []).map(item => item.trim()); return rows.filter(items => items.some(Boolean)).map(items => Object.fromEntries(headers.map((header, i) => [header || `_column_${i}`, items[i] || ""]))); }
async function raw(source: Source, env: Record<string, string | undefined>): Promise<Record<string, unknown>[]> { const base = env.BASE_STEIN_URL; if (base) try { const response = await fetch(`${base}/${encodeURIComponent(source)}`); if (response.ok) { const data: unknown = await response.json(); if (Array.isArray(data)) return data as Record<string, unknown>[]; } } catch { /* fallback */ } const sheetId = env.GOOGLE_SHEET_ID; if (!sheetId) throw new Error("GOOGLE_SHEET_ID belum dikonfigurasi"); const response = await fetch(`https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?tqx=out:csv&gid=${gids[source]}`); if (!response.ok) throw new Error(`Google Sheets ${response.status}`); return parseCsv(await response.text()); }
export async function getArticles(env: Record<string, string | undefined>, source?: Source): Promise<Article[]> { const sources = source ? [source] : (Object.keys(gids) as Source[]); const groups = await Promise.all(sources.map(async current => (await raw(current, env)).map(item => normalize(item, current)).filter((item): item is Article => Boolean(item)))); return groups.flat(); }
export async function getArticle(env: Record<string, string | undefined>, slug: string): Promise<Article | undefined> { return (await getArticles(env)).find(article => article.slug === slug); }
